=== GajicMladen/XML-project/ZigBackend/src/main/resources/Z1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.tim777.rs/dokumentZ1" xmlns="http://www.tim777.rs/dokumentZ1">

    <xs:element name="zahtev_za_priznanje_ziga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="podnosilac" type="TLice"/>
                <xs:element name="punomocnik" type="TLice"/>
                <xs:element minOccurs="0" name="zajednicki_posrednik" type="TLice"/>
                <xs:element ref="opis_ziga"/>
                <xs:element ref="brojevi_klasa_robe_usluga"/>
                <xs:element ref="zatrazeno_pravo_prvenstva"/>
                <xs:element ref="placanje"/>
                <xs:element ref="prilozi"/>
            </xs:sequence>
            <xs:attribute name="broj_zahteva" type="xs:string"/>
            <xs:attribute name="datum_podnosenja" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="drzava" type="xs:string"/>
                <xs:element name="postanski_broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:positiveInteger">
                            <xs:minInclusive value="11000"/>
                            <xs:maxInclusive value="44000"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="mesto" type="xs:string"/>
                <xs:element name="ulica" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="kontakt">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="telefon" type="xs:string"/>
                <xs:element name="email" type="xs:string"/>
                <xs:element name="fax" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TLice">
        <xs:sequence>
            <xs:element ref="adresa"/>
            <xs:element ref="kontakt"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravno_lice">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:sequence>
                    <xs:element name="Naziv" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:sequence>
                    <xs:element name="ime" type="xs:string"/>
                    <xs:element name="prezime" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="opis_ziga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tip_ziga" type="TTipZiga"/>
                <xs:element ref="znak"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="znak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="izgled_znaka" type="xs:anyURI"/>
                <xs:element name="vrsta_znaka" type="TVrstaZnaka"/>
                <xs:element name="boje_znaka">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="boja" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="transliteracija" type="xs:string"/>
                <xs:element name="prevod" type="xs:string"/>
                <xs:element name="opis_znaka" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="brojevi_klasa_robe_usluga">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:positiveInteger">
                            <xs:maxInclusive value="45"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="zatrazeno_pravo_prvenstva">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pravo" type="xs:string"/>
                <xs:element name="osnov" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="placanje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="onsovna_taksa" type="xs:decimal"/>
                <xs:element name="graficko_resenje" type="xs:decimal"/>
                <xs:element name="ukupno" type="xs:decimal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="prilozi">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="primerak_znaka" type="xs:anyURI"/>
                <xs:element name="spisak_robe_usluga" type="xs:anyURI"/>
                <xs:element name="punomocje" type="xs:anyURI"/>
                <xs:element name="generalno_punomocje_ranije_prilozeno" type="xs:anyURI"/>
                <xs:element name="punomocje_naknadno_dostavljeno" type="xs:anyURI"/>
                <xs:element name="opsti_akt_o_kolektivnom_zigu" type="xs:anyURI"/>
                <xs:element name="dokaz_o_pravu_prvenstva" type="xs:anyURI"/>
                <xs:element name="dokaz_o_uplati_takse" type="xs:anyURI"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="TTipZiga">
        <xs:restriction base="xs:string">
            <xs:enumeration value="individualni_zig"/>
            <xs:enumeration value="kolektivni_zig"/>
            <xs:enumeration value="zig_garancije"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TVrstaZnaka">
        <xs:restriction base="xs:string">
            <xs:enumeration value="verbalni"/>
            <xs:enumeration value="graficki"/>
            <xs:enumeration value="kombinovani"/>
            <xs:enumeration value="trodimenzionalni"/>
            <xs:enumeration value="drugo"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== GajicMladen/XML-project/xml-tim11/src/main/resources/data/Z1.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev_za_priznanje_ziga xmlns="http://www.tim777.rs/dokumentZ1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.tim777.rs/dokumentZ1 file:/C:/Users/PC/Desktop/fax/VII_semestar/XML/XML-project/KT2/Z1.xsd">
    <podnosilac xsi:type='TFizicko_lice'>
        <adresa>
            <drzava>Srbija</drzava>
            <postanski_broj>15318</postanski_broj>
            <mesto>Mali Zvornik</mesto>
            <ulica>Kralja PEtra I br 6</ulica>
        </adresa>
        <kontakt>
            <telefon>065421654</telefon>
            <email>mladen@dmsak.com</email>
            <fax>06530321</fax>
        </kontakt>
        <ime>'Mladen'</ime>
        <prezime>'Gajic'</prezime>
    </podnosilac>
    <punomocnik xsi:type='TPravno_lice'>
        <adresa>
            <drzava>Srbija</drzava>
            <postanski_broj>21000</postanski_broj>
            <mesto>Novi Sad</mesto>
            <ulica>Veselina Maslese 2</ulica>
        </adresa>
        <kontakt>
            <telefon>6506132130</telefon>
            <email>korpa@dsmak.com</email>
            <fax>560061032</fax>
        </kontakt>
        <Naziv>Korpa d.o.o.</Naziv>
    </punomocnik>
    <opis_ziga>
        <tip_ziga>individualni_zig</tip_ziga>
        <znak>
            <izgled_znaka>https://www.izgled.com/mojzig</izgled_znaka>
            <vrsta_znaka>graficki</vrsta_znaka>
            <boje_znaka>
                <boja>plava</boja>
                <boja>crvena</boja>
            </boje_znaka>
            <transliteracija></transliteracija>
            <prevod>nyokosuzi</prevod>
            <opis_znaka>licni pecat </opis_znaka>
        </znak>
    </opis_ziga>
    <brojevi_klasa_robe_usluga>
        <broj>2</broj>
        <broj>5</broj>
        <broj>17</broj>
    </brojevi_klasa_robe_usluga>
    <zatrazeno_pravo_prvenstva>
        <pravo>pravo broj 128</pravo>
        <osnov>osnov broj 21 sadmd po ustavu dsaknda</osnov>
    </zatrazeno_pravo_prvenstva>
    <placanje>
        <onsovna_taksa>123</onsovna_taksa>
        <graficko_resenje>450</graficko_resenje>
        <ukupno>965</ukupno>
    </placanje>
    <prilozi>
        <primerak_znaka>https://www.prilog.com/mojzig</primerak_znaka>
        <spisak_robe_usluga>https://www.prilog.com/mojzig</spisak_robe_usluga>
        <punomocje>https://www.prilog.com/mojzig</punomocje>
        <generalno_punomocje_ranije_prilozeno>https://www.prilog.com/mojzig</generalno_punomocje_ranije_prilozeno>
        <punomocje_naknadno_dostavljeno>https://www.prilog.com/mojzig</punomocje_naknadno_dostavljeno>
        <opsti_akt_o_kolektivnom_zigu>https://www.prilog.com/mojzig</opsti_akt_o_kolektivnom_zigu>
        <dokaz_o_pravu_prvenstva>https://www.prilog.com/mojzig</dokaz_o_pravu_prvenstva>
        <dokaz_o_uplati_takse>https://www.prilog.com/mojzig</dokaz_o_uplati_takse>
    </prilozi>
</zahtev_za_priznanje_ziga>
